pipeline {
    agent any
    stages {
        stage('Run Staging') {
            steps {
                // Get some code from a CodeCommit repository
                script{
                    build job: 'PIPELINE-FULL-STAGING', propagate: true, wait:true
                    //echo staging-job.result
                }
            }
        }
    }
}
